<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PVT Plomberie</title>
</head>
    
    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">


    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>


    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

    <!-- Header -->

    <header>

        <nav class="navbar navbar-expand-lg navbar-light fixed-top ">

            <div class="container">

                <a class="navbar-brand" href="#">PVT Plomberie</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav ml-lg-auto">

                        <li class="nav-item active">
                            <a class="nav-link" href="#">Accueil<span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $requestUrl ?>/prestation">Nos prestations</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $requestUrl ?>/about">A propos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $requestUrl ?>/contact">Contact</a>
                        </li>
                    </ul>

                </div>

            </div>
            
        </nav>

    </header>






<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>
    
</main>



<!-- Pied de page commun -->
<footer>
    
    <div class="container">

        <small>Copyright 2019 | PVT Plomberie| <a href="<?= $requestUrl ?>/login">Admin</a> </small>

    </div>

    <div class="adminco">

        <div class="container">

            <ul>

                <?php if(array_key_exists('firstName', $_SESSION)): ?>
                    <li>
                        <a class="button button-primary" href="<?= $requestUrl ?>/admin">Parti admin</a>
                    </li>
                    <li class="layout-right">
                        <p class="welcome">Bonjour <strong><?= $_SESSION['firstName'].' '.$_SESSION['lastName'] ?></strong> !</p>
                        <a class="button button-primary" href="<?=$requestUrl?>/logout">Déconnexion</a>
                    </li>
                <?php endif ?>

            </ul>

        </div>  

    </div>
    
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>





