

<div class="contact">

  <div class="container">

    <form class="generic-form" action="<?= $requestUrl ?>/contact" method="POST">

      <div class="form-group">

        <label for="LastName">Nom</label>
          <input type="LastName" class="form-control" id="LastName" placeholder="Votre nom" name="LastName">

      </div>

      <div class="form-group">

        <label for="FirstName">Prénom</label>
        <input type="FirstName" class="form-control" id="FirstName" placeholder="Votre prénom" name="FirstName">

      </div>

      <div class="form-group">

        <label for="Email">Email</label>
        <input type="Email" class="form-control" id="Email" placeholder="Email" name="Email">

      </div>

      <div class="form-group">

        <label for="Adresse">Adresse</label>
        <input type="Adresse" class="form-control" id="Adresse" placeholder="Adresse" name="Adresse">

      </div>

      <div class="form-group">

        <label for="City">Ville</label>
        <input type="City" class="form-control" id="City" placeholder="Ville" name="City">

      </div>

      <div class="form-group">

        <label for="ZipCode">Code postal</label>
        <input type="ZipCode" class="form-control" id="ZipCode" placeholder="Code postal" name="ZipCode">

      </div>

      <div class="form-group">

        <label for="Why">Sujet</label>

        <select class="form-control" id="Why" name="Why">

          <option value="Devis">Devis</option>
          <option value="Depannage" >Dépannage</option>
          <option value="Entretien">Entretien</option>
          <option value="Intallation">Installation</option>
          <option value="Autre">Autre</option>

        </select>

      </div>

      <div class="form-group">

        <label for="exampleFormControlTextarea1">Votre message</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="Message"></textarea>

      </div>

      <ul>

        <li>
          <input class="button button-primary" type="submit" value="Envoyer">
          <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
        </li>

      </ul>

    </form>
    
  </div>

</div>
