
<!--
<div class="contact">

  <div class="container">

    <form class="generic-form" action="<?= $requestUrl ?>/contact" method="POST">

      <div class="form-group">

        <label for="LastName">Nom</label>
          <input type="LastName" class="form-control" id="LastName" placeholder="Votre nom" name="LastName">

      </div>

      <div class="form-group">

        <label for="FirstName">Prénom</label>
        <input type="FirstName" class="form-control" id="FirstName" placeholder="Votre prénom" name="FirstName">

      </div>

      <div class="form-group">

        <label for="Email">Email</label>
        <input type="Email" class="form-control" id="Email" placeholder="Email" name="Email">

      </div>

      <div class="form-group">

        <label for="Phone">Numéro de téléphone</label>
        <input type="Phone" class="form-control" id="Phone" placeholder="Téléphone" name="Phone">

      </div>

      <div class="form-group">

        <label for="Adresse">Adresse</label>
        <input type="Adresse" class="form-control" id="Adresse" placeholder="Adresse" name="Adresse">

      </div>

      <div class="form-group">

        <label for="City">Ville</label>
        <input type="City" class="form-control" id="City" placeholder="Ville" name="City">

      </div>

      <div class="form-group">

        <label for="ZipCode">Code postal</label>
        <input type="ZipCode" class="form-control" id="ZipCode" placeholder="Code postal" name="ZipCode">

      </div>

      <div class="form-group">

        <label for="Why">Sujet</label>

        <select class="form-control" id="Why" name="Why">

          <option value="Devis">Devis</option>
          <option value="Depannage" >Dépannage</option>
          <option value="Entretien">Entretien</option>
          <option value="Intallation">Installation</option>
          <option value="Autre">Autre</option>

        </select>

      </div>

      <div class="form-group">

        <label for="exampleFormControlTextarea1">Votre message</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="Message"></textarea>

      </div>

      <ul>

        <li>
          <input class="button button-primary" type="submit" value="Envoyer">
          <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
        </li>

      </ul>

    </form>
    
  </div>

</div>
-->

<div class="container">
	 <form action="<?= $requestUrl ?>/contact" method="POST" class="register-form"> 
      <div class="row">      
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="LastName">Nom</label>
               <input name="LastName" class="form-control" type="text">    
           </div>            
      </div>
      <div class="row">      
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="FirstName">Prénom</label>
               <input name="FirstName" class="form-control" type="text">    
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="Email">EMAIL</label>
               <input name="Email" class="form-control" type="email">             
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="Phone">Numéro de téléphone</label>
               <input name="Phone" class="form-control" type="text">             
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="Adresse">Adresse</label>
               <input name="Adresse" class="form-control" type="text">             
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="City">Ville</label>
               <input name="City" class="form-control" type="text">             
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="ZipCode">Code Postal</label>
               <input name="ZipCode" class="form-control" type="text">             
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-4">
              <label for="Why">Sujet</label>

              <select class="form-control" id="Why" name="Why">

                <option value="Devis">Devis</option>
                <option value="Depannage" >Dépannage</option>
                <option value="Entretien">Entretien</option>
                <option value="Intallation">Installation</option>
                <option value="Autre">Autre</option>

              </select>             
           </div>            
      </div>
      <div class="row">
           <div class="col-md-4 col-sm-4 col-lg-12">
           <label for="exampleFormControlTextarea1">Votre message</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="6" name="Message"></textarea>           
           </div>            
      </div>
      <hr>
      <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6 col-lg-6">
           <button class="btn btn-default logbutton" type="submit" value="Envoyer">Envoyer</button>           
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6 col-lg-6">
           <button href="<?= $requestUrl ?>" class="btn btn-default regbutton">Annuler</button>
          </div>          
      </div>    
    </form>
</div>
